# .github/workflows/test-workflow.yml
name: Simple Test Workflow

on:
  push:
    branches: ['master']
  workflow_dispatch: # Allows manual trigger

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"